source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'OzneriFamily' do
    pod 'DateTools','~> 1.7.0'
    pod 'IQKeyboardManager','~> 4.0.7'
    pod 'UICountingLabel','~> 1,.4.0'
    pod 'KMNavigationBarTransition','~> 0.0.10'
    pod 'Bugly','~> 2.4.6'
end
