source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'OzneriFamily' do
    pod 'DateTools'
    pod 'IQKeyboardManager'
    pod 'UICountingLabel'
    pod 'KMNavigationBarTransition'
end
