source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'OzneriFamily' do
    pod 'DateTools','~> 2.0.0'
    pod 'IQKeyboardManager','~> 4.0.8'
    pod 'UICountingLabel','~> 1.4.0'
    pod 'KMNavigationBarTransition','~> 1.0.0'
    pod 'Bugly','~> 2.4.6'
#    pod 'JSPatchPlatform'
end
